# MySQL utf8类型不能存储Emoji的解决方案

原因:
    mysql的utf8实际是utf8mb3类型的, 不支持真正的utf8mb4

解决方案:
    将需要的某个字段改成utf8mb4即可

依赖:
    mysql5.5.3

执行方案:
# 查看原先的字段类型
show full columns from account_v2_55;
> +------------------------+---------------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
> | Field                  | Type                | Collation          | Null | Key | Default | Extra | Privileges                      | Comment |
> +------------------------+---------------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
> | account_info_3p        | text                | utf8_general_ci | NO   |     | NULL    |       | select,insert,update,references |         |
> +------------------------+---------------------+--------------------+------+-----+---------+-------+---------------------------------+---------+

# 改成现在的类型
alter table account_v2_55 MODIFY COLUMN account_info_3p text CHARACTER SET utf8mb4 NOT NULL;
> +------------------------+---------------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
> | Field                  | Type                | Collation          | Null | Key | Default | Extra | Privileges                      | Comment |
> +------------------------+---------------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
> | account_info_3p        | text                | utf8mb4_general_ci | NO   |     | NULL    |       | select,insert,update,references |         |
> +------------------------+---------------------+--------------------+------+-----+---------+-------+---------------------------------+---------+


代码:
db_url = "mysql+mysqldb://root:root@127.0.0.1:3306/global_account?charset=utf8mb4"
engine = create_engine(db_url)
...

# 因为python不认识这个utf8mb4编码
import codecs
codecs.register(lambda name: codecs.lookup('utf8') if name == 'utf8mb4' else None


# 补充：对于一个新表，在sqlalchemy定义的时候,增加一个collation即可
account_info_3p = Column(TEXT(collation='utf8mb4_general_ci'))


参考文档:
https://stackoverflow.com/questions/2108824/mysql-incorrect-string-value-error-when-save-unicode-string-in-django
